name: Lint

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets
      - name: Clippy no_std
        run: cargo clippy --no-default-features
      - name: Clippy with features
        run: cargo clippy --features tracing,create-fixed,with-serde
      - name: Clippy privacy policy
        run: cargo clippy -p aurora-evm --all-targets --features privacy,tracing,create-fixed,with-serde
      - name: Clippy with features for aurora-evm-jsontests
        run: cargo clippy -p aurora-evm-jsontests --features dump-state

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Build NoStd
        run: cargo build --no-default-features

      - name: Build for feature (tracing & serde)
        run: cargo build --features tracing,with-serde
